### ISSUE TITLE
reCaptcha v2 does not work if third party cookies are disabled and does not give feedback to the user

### ISSUE THREAD

**Issue by DanielaValero** [google/recaptcha#155]
When the third party cookies are disabled in the browser, the selection of the user of the tiles, does not get stored, therefore the user is not able to solve the captcha.

It is true, that if the user disables explicitly the third party cookies, or enters the browser in a privacy mode, they would know that any feature that requires cookies will not work as expected.

However, is also true, that in order to provide a better user experience, we should give feedback to the user, when a feature is not working.

Would it be possible to add a note to the user about this?

The feature would theoretically be something like this:

From the reCaptcha to detect if the cookies are not enabled, and if so, render a string to tell the user that the reCaptcha is not going to work, and in order to have it working, the user should enable the third party cookies in the browser.

## Steps to reproduce
1. Disable the third party cookies in chrome or FF
2. Clean the cookies
3. Reload the browser
4. Go to any of the next links, and try to solve the reCaptcha when it shows the tiles

https://www.google.com/recaptcha/api2/demo
http://vividcortex.github.io/angular-recaptcha/

**Comment by mastix** [comment]
We're facing the same issue. Our corporate browser has 3rd party cookies disabled by default, which means that we're having a hard time solving the reCaptcha riddles. :(

**Comment by Kasijjuf** [comment]
What is the domain of the third-party cookie reCaptcha uses?

**Comment by creeper123123321** [comment]
The domain that recaptcha uses is google.com and www.google.com

**Comment by timreeves** [comment]
My own experience is, with Chromium and FF, both with 3rd party cookies turned off,
reCaptcha V2 can (nowadays) still be used, but it did try to set 2 cookies (blocked):
- google.com / CONSENT
- google.com / NID

And anyway it uses calls to 3rd party websites:
- fonts.gstatic.com
- www.gstatic.com     Logo, JS, CSS
- www.google.com    reCaptcha-API, JS

**Comment by theking2** [comment]
Hi Tim, 
With third party cookies disabled recaptcha does not really work. It keeps on asking new clicks for store fronts, roads, streetsigns and autobusses. After about 15 min of useless clicking Google servers seem to give up and assume that only a human being spends so much time aimless clicking.
What cookies should be enabled to have recaptcha working? (Sony is driving me crazy with this, why no implement a decent 2FA?)

**Comment by rowan-m** [comment]
This isn't directly related to the PHP code which is what this repo focuses on. However, you might want to look at the v3 support in the most recent release. That uses a wholly invisible reCAPTCHA that just returns a confidence score for the request. This might alleviate some of your issues. Example hosted at https://recaptcha-demo.appspot.com/recaptcha-v3-request-scores.php

**Comment by lschad** [comment]
this is still an issue

**Comment by msc1** [comment]
you can not follow any security and privacy practises with google recaptcha **protecting** a website. For years, we've (security/privacy concious people) been training your AI algorithms with the new versions of recaptcha. I am sick and tired off not being able to visit sites. A fix must be made or I think webmasters will turn away to alternative captcha solutions. There are very good alternatives around there.

**Comment by jamb0ss** [comment]
fuck recaptcha

**Comment by wizajay** [comment]
> 
> 
> you can not follow any security and privacy practises with google recaptcha _protecting_ a website. For years, we've (security/privacy concious people) been training your AI algorithms with the new versions of recaptcha. I am sick and tired off not being able to visit sites. A fix must be made or I think webmasters will turn away to alternative captcha solutions. There are very good alternatives around there.

Totally agree. I have added nonces and still cookie warnings pop up. Anyways, google will deprecate v2 soon like they did to v1 and then we'll have to sit like dumb ducks without allowing google to score our users. It's time we form a anticaptch club. Can you suggest any good recaptcha alternatives you use?

**Comment by vertigo220** [comment]
Been posting in another issue, not directly related to this, but definitely part of the annoyance that is reCaptcha. While the cookie situation is likely partially innocent, i.e. a way to have a good idea of whether a "user" is a human or a bot, I'm convinced it's also at least partially designed to force Google cookies on systems regardless of other settings (blocking 3rd-party cookies, deleting Google cookies, etc) in order to prevent the massive time waste of having to do captchas all the time, and spend 3+ minutes on them each time. I'm also convinced they are, both in general and especially in these cases, using people to train their systems. Anyways, as discussed in the other issue, I have serious concerns about v3, and suspect it will be even worse than v2, since it will quite likely simply block people instead of offering them the ability to prove they're human (even if that does take FAR longer than it should and still often fail). And it seems to me the requirement for users to have Google cookies on their systems just to use a number of unrelated sites, not to mention the fact said cookies aren't even disclosed, is in [violation of GDPR](https://stackoverflow.com/questions/50439294/prevent-google-recaptcha-setting-a-cookie-gdpr) and possibly (though, sadly, unlikely) FTC rules.

**Comment by adriannadiaz** [comment]
I am using the uBlock Origin Ad Blocker and no matter how many times I try to solve the ReCatpchas, and they show up everywhere (even my bank!) due to lazy web developers, it still does not accept I am a human, or at least I thought I was one until now, am I? 

ReCaptcha is just a *cookie-based* scheme to put Google Cookies... There is in fact no smart heuristics detecting humans vs. robots.  I refuse to work for Google and specially not if I am not getting a salary !!!

🤖

**Comment by fjallarefur** [comment]
I can't log in to several websites, because they use reCaptcha, which gives me 10-20 challenges/unpaid work assignments for Google, and then, upon completion, refuses to let me through. I assume this is because I block tracking domains and/or third-party cookies.

**Comment by chorliya** [comment]
I've not seen the (backend) interface for reCAPTCHA, but I'm assuming there's a way to set for less screens to be displayed to the visiting user - that's different than (any) default settings. Very rarely I do come across a reCAPTCHA solve which lets me through after just one round (maybe two?); as opposed to the default three-or-more. 

^^ So, in theory, webmasters could re(configure) to make everyone's lives easier - except this seems to be rarely done. :/

**Comment by sylvain261** [comment]
Same issue with reCaptcha v3.

**Comment by Neobond** [comment]
Is this also the reason it is suddenly being triggered more often on multiple websites? Due toGoogle and Firefox requiring block of third party cookies?

**Comment by karlhorky** [comment]
@rowan-m @yingliu-google this comes up as one of the top results when searching for "deprecating third party cookies recaptcha" on Google, related to [Chrome's upcoming third-party cookie deprecation](https://developers.google.com/privacy-sandbox/blog/cookie-countdown-2023oct)

Even though this repo is focused on PHP code, would it be possible for you to reach out to the JavaScript reCAPTCHA team internally at Google and post back with a link for everyone here to follow progress of reCAPTCHA v2 and v3 compliance with these 3rd party cookies rules in Chrome?

**Comment by Toxiapo** [comment]
Is there any information on whether this matter has been pursued further or discussed elsewhere? I anticipate that this issue could pose challenges for many websites in the near future.

**Comment by samdutton** [comment]
See https://github.com/privacysandbox/privacy-sandbox-dev-support/issues/228#issuecomment-1885828939: 

> No action is required. reCAPTCHA (v2 and v3) will both continue to work as 3PC are deprecated, and the team is actively investing in alternative technologies.

**Comment by karlhorky** [comment]
Thanks for that @samdutton ! Good to see that message from the Google engineering lead for reCAPTCHA @chhamilton 🙌
