### ISSUE TITLE
grecaptcha is not defined

### ISSUE THREAD

**Issue by neoman666** [google/recaptcha#207]
I would like to use recaptcha together with [query validate](https://jqueryvalidation.org/). I have used the [following code](https://bubinga.co/combining-googles-recaptcha-and-jquery-validate/). The validation works, but I get the following error in the javascript console.

grecaptcha is not defined

Who can help me?

**Comment by lucasbasquerotto** [comment]
A bit late, but for anyone having such error, try to include the recaptcha script (`<script src='https://www.google.com/recaptcha/api.js'></script>`) before every other script in your page. That error seems due to some race condition.

**Comment by Sergeyamir** [comment]
I tried to do that (include the recaptcha script before every other), but the same problem now: recaptcha works well in Chrome, but in IE & Edge even did not displayed (though earlier worked well with them too).

**Comment by lucasbasquerotto** [comment]
@Sergeyamir  I don't think your problem is the same as the OP. Is your problem that `grecaptcha` is undefined (when you debug you see it as undefined, do you receive a console error?) **or** some other? If the later, I recommend opening another issue. 

It might be good to test a simple use case with a blank html page that just includes the script to see if it works in the browsers you mentioned.

**Comment by rowan-m** [comment]
I'd suggest taking a look through https://developers.google.com/recaptcha/docs/display#explicit_render where it talks about ensuring you're including the library correctly in order to avoid any race conditions.
