### ISSUE TITLE
shame on you and go to hell

### ISSUE THREAD

**Issue by djmisterjon** [google/recaptcha#252]
shame on you and go to hell.
Waste time on you ugly recaptcha code , never solved after x100 attempt and lost all work..
you rot internet with your recaptcha.

**Comment by hypnoboutique** [comment]
wow...

**Comment by workguy66** [comment]
@djmisterjon 
Change `$recaptcha = new \ReCaptcha\ReCaptcha($secret);` with `$recaptcha = new \ReCaptcha\ReCaptcha($secret, new RequestMethod\CurlPost());`

**Comment by djmisterjon** [comment]
I will cleared up my criticism, which was not very constructive.
this is not the point seen webmaster here but from the user's point of view.
Since several months I fall several times on these captcha impossible to solve and each time obliged me to ambandoner my work, my message or my login.

This system is a perfect example of productivity constraints for the web.

which made me overflow the drop of the vase!
I was running an experiment on jsperf to test my engine, and at the moment of validating, still overpowers this captcha imposible to solve.
After 30 minutes try to solve this imposible system.
I have to give up again.

If this project does not make polimi, it is that most users are unaware of hosting it here, but just take a look at the web to see all the frustration and loss of productivity of **this devilish system.**

https://www.google.ca/search?ei=PXGFW-m6JcbVzwL9p4LQAg&q=captcha+hell&oq=captcha+hell&gs_l=psy-ab.3..0i7i30i19k1j0i19k1j0i8i30i19k1.12232.12232.0.12482.1.1.0.0.0.0.93.93.1.1.0....0...1c.1.64.psy-ab..0.1.93....0.7zB6vD_2vJM

https://www.google.ca/search?ei=SnGFW96AM8fazgKcjIzABw&q=captcha+fuck&oq=captcha+fuck&gs_l=psy-ab.3...51777.52206.0.52476.4.4.0.0.0.0.134.355.3j1.4.0....0...1c.1.64.psy-ab..0.3.291...0j0i22i30k1.0.Np2rN3JoxoM

i let you search by yourself.
my comments do not personally aim the developer but the project here.
voial!

**Comment by rowan-m** [comment]
I would suggest looking at v3 of the reCAPTCHA API where it provides a score per request rather presenting challenges to the user. You can either implement this on your own sites or encourage the owners of sites you use to update to this.
https://recaptcha-demo.appspot.com/recaptcha-v3-request-scores.php
https://github.com/google/recaptcha/blob/master/examples/recaptcha-v3-request-scores.php

I appreciate that the challenges can be frustrating to solve, it is an ongoing race to find the right balance between preventing automated spam and still making things usable for humans. Hopefully it will continue to get better.

If there's a specific issue with the PHP client in this repo, I'm happy to address it. Otherwise I'll be closing this as it's discussion of the service itself rather than the code hosted here.

**Comment by ip1981** [comment]
I am a robot: https://www.youtube.com/watch?v=U2q1f1ECMP4
