### ISSUE TITLE
Recaptcha slow and score at 0.1

### ISSUE THREAD

**Issue by mircofUPO** [google/recaptcha#259]
Hello, I'm redirected here from Google support. The problem is that recaptcha is very slow and always wrong. On this site https://recaptcha-demo.appspot.com/recaptcha-v3-request-scores.php on chrome with logged google account, my score is 0.1 and I'can't solve any recaptcha. If I try on another browser without login in my google account, the score is 0.7 and, in fact, I can solve recaptcha.
The problem seems related to my google account. Is it possible to increase this score and solve the problem? I'm not using VPN and my chrome version is up to date.

**Comment by rowan-m** [comment]
I wouldn't advise focusing too much on the score returned by the example page. That example is intended to show an approach to implementing the v3 API using the PHP code hosted here. The score returned is specific to that particular request and is not an indicator about the status of your Google account.

When using the v3 API on your own site, the score indicates the confidence in which the service has that this is a non-automated request. It is not a definitive answer, only an indicator. A low score can be used as a prompt for additional verification on an action - for example, a confirmation SMS - rather than blocking a user entirely.

**Comment by TimGoll** [comment]
reCaptcha is so annoying. I always have to solve puzzles for a minute. And they fade in so slow. And there is no way to reset your score. I don't know what to do
