### ISSUE TITLE
reCaptcha my gmail account score 0.1; why am i blacklisted ?

### ISSUE THREAD

**Issue by Demky** [google/recaptcha#260]
I don't know why but with my main gmail account Captcha are very slow and complicated.
it's a very old account, linked with my android, chrome, google map history etc...) and it got a score of 0.1 : https://recaptcha-demo.appspot.com/recaptcha-v3-request-scores.php

- When i'm using my gmail/chrome account used only at school/work (i created it 3-4month ago when i started the web developer school) the captcha are easy (only one checkbox) and my score is +/-0.7 
- If i use chrome without any account, the captca are easy.
- Everytime i swap to my main account the captcha are very hard.

Google support forum told me to write here for my problem cause nobody was able to help me!

Why is my google account blacklisted ? what did i do wrong ? i have been a fan of google since the begining and i have no idea why i got blacklisted...

I can give my gmail account name in private if needed.

edit : I'm from France, my ISP is "Free" and i don't use vpn.

**Comment by rowan-m** [comment]
I wouldn't advise focusing too much on the score returned by the example page. That example is intended to show an approach to implementing the v3 API using the PHP code hosted here. The score returned is specific to that particular request and is not an indicator about the status of your Google account.

When using the v3 API on your own site, the score indicates the confidence in which the service has that this is a non-automated request. It is not a definitive answer, only an indicator. A low score can be used as a prompt for additional verification on an action - for example, a confirmation SMS - rather than blocking a user entirely.

**Comment by Demky** [comment]
so you just ignore my probleme and close the ticket ?
reCaptcha isnt usable with my main gmail adress... and google forum sent me there for help.

Where am I supposed to ask for support if this is the wrong thread ?

**Comment by rowan-m** [comment]
Could you link me to the thread in the forum where they directed you here?

**Comment by manish-vashi** [comment]
i am having issues where recaptcha always returns 0.1 when browsing with firefox. All other browsers return a score of 0.9
