### ISSUE TITLE
Can Recaptcha V2 and V3 Be Used on The Same Web Page?

### ISSUE THREAD

**Issue by touhonoob** [google/recaptcha#279]
An example use case is that a site might want to verify an user getting a low score from V3 with V2.

**Comment by rowan-m** [comment]
You can see (examples of multiple v2 widgets)[https://developers.google.com/recaptcha/docs/display#example] here. I haven't tried mixing v2 and v3, but I can give it a go and see if I can pop an example up.

**Comment by therealcaii** [comment]
Anything updates on this?

**Comment by splinter89** [comment]
Why use v3 at all in this case?
Let google decide if the score is too low and verify the humanness - all under v2.

**Comment by touhonoob** [comment]
@splinter89 to save time for legit users

**Comment by splinter89** [comment]
Sorry, I don't see how you can save time without allowing more suspicious traffic.
If I were okay with users solving recaptcha puzzles, I would simply use v2.

Anyway, you'll need to load api.js twice to use both recaptcha's on the same page.
v3 loads faster and doesn't require `grecaptcha.reset()` to get multiple tokens.
```html
<script src="https://www.google.com/recaptcha/api.js?onload=v2_onload"></script>
<script src="https://www.google.com/recaptcha/api.js?onload=v3_onload&render=V3_SITE_KEY"></script>
<div class="g-recaptcha" data-size="invisible" data-sitekey="V2_INVISIBLE_SITE_KEY" data-callback="v2_callback"></div>
<script type="text/javascript">
    function v2_onload() { console.log('v2 loaded'); }
    function v3_onload() { console.log('v3 loaded'); }
    function v2_callback(token) { console.log('v2 token: ' + token); }
    function v3_callback(token) { console.log('v3 token: ' + token); }

    // call these manually
    function test_v2() { grecaptcha.execute(); }
    function test_v3() { grecaptcha.execute(V3_SITE_KEY/*, {action: '...'}*/).then(v3_callback); }
</script>
```

**Comment by yisusans** [comment]
I've done this and occasionally I get an error on my site that reads `Invalid site key or not loaded in api.js`.  When I inspect the error, it turns out my v3 keys are being used for v2.  This only happens occasionally.  Does anyone else have this issue?

**Comment by ivan-slepchenko** [comment]
@yisusans Have you fixed your problem somehow?

**Comment by yisusans** [comment]
Yeah, I have...there was an issue w/ the react library I was using.  Thanks!

**Comment by flaviossantana** [comment]
Hello, is it possible to use both versions (v2 and v3) in the same project?
When trying to use I get the error below:

`core.js:14597 ERROR Error: Invalid site key or not loaded in api.js: 6Ld4cH8UAAAAAEQo7ePHMKchWah2IPc93-LlzPDV
    at Object.rG [as execute] (recaptcha__pt_br.js:522)`

**Comment by yisusans** [comment]
i had the same issue.  how are you loading v2?

**Comment by yisusans** [comment]
but this might be a race condition issue w/ the way you're loading recaptcha v2 & v3.

**Comment by flaviossantana** [comment]
Hello, I was able to solve the problem.
It was missing calling the method:

`
// clean script to make sure siteKey is set correctly (because previous script could be incorrect)
this.scriptService.cleanup ();
`

before calling the method:

`this.reCaptchaV3Service.execute ()`


With that I solved the sitekey problem:

`
ReCaptchaV23DemoComponent.html: 171 ERROR Error: Invalid site key or not loaded in api.js: 6Let_5gUAAAAANi3fdTLGzZzXIR1DKUc6EuV9Ev0
    at Object.rG [as execute] (recaptcha__en.js: 522)
    at recaptcha_v3.service.ts: 31
    at ZoneDelegate.push ../ node_modules / zone.js / dist / zone.js.ZoneDelegate.invoke (zone.js: 391)
    at Zone.push .. / node_modules / zone.js / dist / zone.js.Zone.run (zone.js: 150)
    at NgZone.push ../ node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular (core.js: 17248)
    at recaptcha_v3.service.ts: 30
    at script.service.ts: 32
    at ZoneDelegate.push ../ node_modules / zone.js / dist / zone.js.ZoneDelegate.invoke (zone.js: 391)
    at Object.onInvoke (core.js: 17289)
    at ZoneDelegate.push .. / node_modules / zone.js / dist / zone.js.ZoneDelegate.invoke (zone.js: 390)
`

Thank you! / Obrigado!

**Comment by d0coat01** [comment]
Here's an approach that seems to work quite well for us.

According to [ReCAPTCHA's API](https://developers.google.com/recaptcha/docs/display#explicitly_render_the_recaptcha_widget), 
![Screen Shot 2019-11-19 at 3 32 45 PM](https://user-images.githubusercontent.com/4550944/69195924-e4287f00-0ae1-11ea-97f8-fa8266f344db.png)

It is recommended to include your onload callbacks first.

The api is assigned to `window.grecaptcha` when it is loaded. Knowing that, you can clone the api into two separate variables as shown below:
```html
<script>
  function recaptchaV2Callback() {
    window.grecaptchaV2 = Object.assign(Object.create(Object.getPrototypeOf(window.grecaptcha)), window.grecaptcha)
  }

  function recaptchaV3Callback() {
    window.grecaptchaV3 = Object.assign(Object.create(Object.getPrototypeOf(window.grecaptcha)), window.grecaptcha)
  }
</script>

<script src="https://www.recaptcha.net/recaptcha/api.js?onload=recaptchaV2Callback&render=explicit" async
  defer></script>

<script
  src="https://www.recaptcha.net/recaptcha/api.js?onload=recaptchaV3Callback&render={{ YOUR_V3_SITE_KEY }}"></script>
```

You can then just call each api separately such as `window.grecaptchaV3.execute(...)`.

**Comment by rexlam0630** [comment]
Official way: https://developers.google.com/recaptcha/docs/faq

**Comment by NautillusSs** [comment]
Using the official way, how did you differentiate in the backend between v2 and v3 to use the correct secret key for the 'verify' API?

**Comment by diliprai-omiba** [comment]
gg

**Comment by rowan-m** [comment]
Closing old issues that are not related to the PHP client code.
