### ISSUE TITLE
we find that V3 validation scores very low (0.1)

### ISSUE THREAD

**Issue by youyisx** [google/recaptcha#304]
HI, when we load a web page in the APP that only provides recaptcha services, we find that V3 validation scores very low (0.1). Is there a solution?

**Comment by ltctech** [comment]
I have the exact same issue. When I have a page with a lot of content I get 0.7 and 0.9. While a page with a simple form nearly always gets 0.1. Same site otherwise.

**Comment by klevak** [comment]
We are seeing the same issue and many users get a .1 for not apparent reason

**Comment by gingerlime** [comment]
related #248

**Comment by Pfenya** [comment]
We are seeing similar things on a production site with a lot of users complaining about not being able to use a sign up form and the admin console shows a large growth of .1 scores since yesterday.

**Comment by ammmmb** [comment]
fuck you! google recaptcha!

**Comment by MonDeveloper** [comment]
Issue still open.
Since it probabily relies on the ML under the hood it is quite hard to find similarities but it's pretty sure it is bugged.
Same interaction made by IE11 and Chrome (both Incognito, both from the same PC) takes 0.1 and 0.3 using IE11 and 0.9 using Chrome.

**Comment by felixck12** [comment]
Facing  a similar issue. Since adding v3 to our login form which is a simple form with a two input fields, we have been seeing low scores mostly 0.1 since releasing this to our production. This seems to have impacted other actions on different pages also using v3 which are now showing low scores in our admin console.

Are there some best practices that is we are missing? I was not able to find much in the documentation.

**Comment by dusnoki** [comment]
We are having the same problem. A couple of days ago we started getting lots of 0.1 scores. Even our own developers are getting bad scores. It's all a bit flakey, sometimes the score is good, sometimes not. It seems to be affecting the domains which are behind a CDN (Cloudfront) more than the ones that aren't. But it might be only a fluke. Had to disable recaptcha for now.

**Comment by yoyoloftis** [comment]
Same issue for us. We are using recaptcha v3 on some of our website forms. On 4/21/21 (two days ago), we started experiencing super low scores of 0.1 and 0.3, even for real users. In testing myself, I am sometimes getting 0.7 score, and sometimes getting a 0.1 or a 0.3, depending on browser. Developer partners get same results. This is super frustrating, since we have set up some blockers and error messages for end users in these low score scenarios. This is bad for customer service. It would be good to know if Google has changed anything recently. Because we have not made any changes, and it was working great until this week.

**Comment by armellarcier** [comment]
Same here. We changed the `action` strings sent for each specific verification and our scores are good again.
So we appended a dynamic suffix to all `action` strings (the current date formatted `YYYYMMDD`).
We're hoping this will make our score consistently better.

**Comment by rowan-m** [comment]
Closing old issues that are not related to the PHP client code.
