### ISSUE TITLE
Kill recaptcha

### ISSUE THREAD

**Issue by Chaython** [google/recaptcha#320]
Why does it sometimes have 3 second animations to show the next images?
Is it a bot that set the images in the first place? Because I always select all the correct images and it still gives me multiple other sets saying "try again"
Sometimes I spend 2 minutes selecting so many damn pictures
It didn't use to be this annoying, but now-a-days when I go to kijiji every single message asks for recaptcha and in the past week I've spent 2hours filling recaptchas

Recaptcha needs to die

**Comment by Chaython** [comment]
Why doesn't recaptcha have some cache saying I just filed the recaptcha 30 times today successfully...

**Comment by bobmcdouble3** [comment]
You want to know why? It's by design, in order to FORCE you into selling your soul to Google. Do any of the following apply to you?

1. You use a VPN, Tor, or for some reason have a non-residential ip address
2. You don't use Chrome
3. You are not signed into Google
4. You use AdBlock, or a similar program
5. You use Privacy Badger, or a similar tracker blocker
6. You use DDG, or an alternative search engine

If so, Google is purposefully wasting hours of your time, to turn you into another Google slave. These practices are blatantly illegal, immoral, and anti-competitive. This is censorship. 

Stay strong, Chaython.

**Comment by Chaython** [comment]
Ya, pretty much, need to let them pound my anus with tracking cookies.
Recaptcha needs to be smacked with some anti-trust; perhaps a GDPR fine for forcing this strict tracking?
It still goes through, but if you block some of their trackers it will give you more and more sets. If you white list all google and affiliated domains, then you can complete recaptcha in 1 set. The image fade in/out is also instant if you whitelist all, I do not understand why they make the fade in like a 5 second animation if you have certain domains blocked....

**Comment by trialism** [comment]
This "service" should be banned in EU. Period. The people who invented it are scum.

**Comment by ammmmb** [comment]
fuck you! google recaptcha!

**Comment by rowan-m** [comment]
Unrelated to client.
