### ISSUE TITLE
ReCaptcha v3 return "invalid-input-response"

### ISSUE THREAD

**Issue by MattTrovao** [google/recaptcha#321]
I am trying install reCaptcha v3 in a local website, in the future the website will be launched, but when i send the form I receipt the following message:"object(stdClass)#1 (2) { ["success"]=> bool(false) ["error-codes"]=> array(1) { [0]=> string(22) "invalid-input-response" } }" 

I use this video as base of who install the reCaptcha: https://www.youtube.com/watch?v=zGNH_lbpmm8  

Here is my code:

FOOTER.PHP

<script>
	grecaptcha.ready(function() {
	  grecaptcha.execute('SITE-KEY', {action: 'homepage'}).then(function (token){
		document.getElementById('g-recaptcha-response').value="token";
	  })
	});
</script>

---

ENVIAR.PHP

function getCaptcha($SecretKey){
    $response = file_get_contents("https://www.google.com/recaptcha/api/siteverify?secret=SECRET-KEY&response={$SecretKey}");
    $return = json_decode($response);
    return $return;
};
$return = getCaptcha($_POST['g-recaptcha-response']);
if ($return->success == true && $return->score > 0.7){
    //PHP MAILER CODE
}else{
    var_dump($return); 
}
    

The var_dump in else statment is just for test, when I finish will print a mesage for the user.

**Comment by ammmmb** [comment]
fuck you! google recaptcha!

**Comment by rowan-m** [comment]
`invalid-input-response` likely means that something in your  request to the reCAPTCHA service was not correctly formatted. Hard to tell from your code, but the use of `define()` to create a constant in that video leads to code that's quite confusing to read. I'd consider putting the keys into variables rather than constants, as per [the examples in this repo](/google/recaptcha/tree/master/examples).
