### ISSUE TITLE
There are no taxis in this photo

### ISSUE THREAD

**Issue by ipullin** [google/recaptcha#338]
The yellow car clearly shows it’s a business of mufflers and brakes. You can’t continue unless you click a square.
![8ED1C03A-25AB-4B0E-9401-2974ED32B94C](https://user-images.githubusercontent.com/19356068/68855809-285afe80-0733-11ea-9526-23de910890d1.png)

**Comment by rowan-m** [comment]
Fair point, that is actually a beautiful example of a first generation [Oldsmobile 88](https://en.wikipedia.org/wiki/Oldsmobile_88), produced between 1949 - 1953. There's plenty of evidence of this car being used as a patrol car in popular culture, notably in ["Highway Patrol"](https://www.imcdb.org/vehicle_370022-Oldsmobile-88-1956.html) only a few year's after that model's release. There was also a brief resurgence in its use in 1990's [movies](https://www.imcdb.org/vehicle_55886-Oldsmobile-88-Futuramic-1949.html) and [mini-series](https://www.imcdb.org/vehicle_752283-Oldsmobile-88-1955.html) when they wanted to portray a period cop car. That said, this may be purely artistic licence as I'm not able to find any indication these were in use by any real law enforcement agency. As a side note, fast-forward a few decades to the Delta 88 submodel for one that fits the bill for an iconic squad car. No cinema or television references to it as a taxi though.

This particular car is sat outside [Tobince Mufflers & Brakes in London, Ontario](https://www.google.co.uk/maps/@43.0029467,-81.1820736,3a,15y,125.61h,82.76t/data=!3m6!1e1!3m4!1sR7qA0cwAOC15meegVRtv_w!2e0!7i16384!8i8192). I'm unsure if the yellow is the original colour, if they also resprayed the body when adding their advertising livery. Judging by the rust on the lower section of the driver's side door and how it doesn't appear to affect the lettering, I suspect the shop has not resprayed since acquiring it. That said, the [average temperature](https://weatherspark.com/y/18239/Average-Weather-in-London-Canada-Year-Round) in winter there is 16° F which would certainly merit salting the roads and then hitting 29% humidity in summer - that's a recipe for rust on a roadside car right there! So, take my opinion with a pinch of... scepticism.

There's also a striking visual similarity to the [Checker Motors Model A4](https://en.wikipedia.org/wiki/Checker_Motors_Corporation) - also known as the quintessential New York taxi cab. Although, the A4 has a far more distinctive square grill which is an easy differentiator - but to the untamed eye, I admit it's hard to spot.

However, there is a [first-hand account from Paul Niedermeyer](https://www.thetruthaboutcars.com/2009/11/curbside-classic-review-1951-oldsmobile-super-88/) where he refers to,

> Herr Miller’s Olds was THE taxi to hire for special family outings, thanks to its roominess compared to the Mercedes 180 Diesels it shared with the downtown taxi stand. Well, that was the parents’ reason; mine was because of its burbling Rocket V8.

Now, while that particular reminiscence is from Australia it does raise the possibility that the car in question may have been a taxi at some point in its life. However, it is clearly not a taxi at present and so in this case you are correct. You can tap on the 🔄 button in the lower left to load a new challenge, however I will pass on the feedback though. My long-term advice here would be to suggest to VoIPCloud that they consider updating their implementation to reCAPTCHA v3 which provides a confidence score as opposed to the challenge.
