### ISSUE TITLE
Is it possible to fool invisible captcha?

### ISSUE THREAD

**Issue by UndyingMid** [google/recaptcha#343]
Hello,
I work on an online game. We had a huge bot problem and a few months ago we got recaptcha. It seems to be doing well. We caught a lot of cheaters and they admitted to cheating. 
We are starting to have some accounts pop up that have perfect 90 scores on their recaptcha activities, but their game logs look a lot like cheating. For instance, there are two activities that take at most 3-4 seconds to complete. You do one and then have to make a few inputs and then you can complete the other. There are a few accounts that are completing both within a second. It's not possible without scripts, but their recaptcha scores are 90s. 
They aren't using a blocker either because almost all of their actions are being scored. 
Is there something they could be doing to fool recaptcha or is it just weak vs some types of bots. 
Any help would be great.

**Comment by PavMel** [comment]
Hi, @UndyingMid. I'm got the same problem. I'm did some research and have not a good news for you and others, because Recaptcha v3 not a "silver bullet".  

How operator of bots might getting extremely high Recaptcha score(0.9):
-  do not spoofing user agent
-  getting fresh residential ip address from any proxy provider
-  doing some activities with google services, like search a little bit in google.com
-  obtain gmail account
-  doing some activities with google services

**Comment by rowan-m** [comment]
Closing old issues that are not related to the PHP client code.
