### ISSUE TITLE
reCAPTCHA issues with Brave

### ISSUE THREAD

**Issue by ryanbr** [google/recaptcha#407]
Not sure if this correct place to report, but we've had many reports of reCAPTCHA failing or "Please try again." error message when submitting.  If someone can take a look?

Our issue report: https://github.com/brave/brave-browser/issues/12289

**Via our forums:**
https://community.brave.com/t/recaptcha-falsely-recognizes-browser-as-incompatible/172312
https://community.brave.com/t/recaptchas-arent-accepting-responses/172904/26
**Reddit:**
https://old.reddit.com/r/brave_browser/comments/jf9vfi/recaptcha/
https://old.reddit.com/r/brave_browser/comments/jefuj1/recaptcha_service_no_longer_working_with_brave/

Example on https://recaptcha-demo.appspot.com/recaptcha-v2-checkbox.php
https://secure.fanboy.co.nz/gif/recaptca2.gif
https://secure.fanboy.co.nz/gif/recaptca1.gif

**Comment by fragtion** [comment]
All I do know is that I just sat for over 10 minutes trying to pass a single Recaptcha... I must have clicked several hundred fire hydrants, crosswalks, bicycles, and busses in one instance, not to mention the new blocks which each took minutes to load. How cool! Can I have my stolen time back please, Google?

**Comment by snowbound** [comment]
Paypal.com with 2FA is still acting up in Version 1.17.46 Chromium: 86.0.4240.111 (Official Build) beta (64-bit). I disabled sheilds and uBlock origin and still unable to login after 4 or 5 captchas. Switched over to MS Edge Beta and no issues.

**Comment by philly-vanilly** [comment]
>Which browser would you want to use every day?
The one that respects my privacy and doesn't take users of other browsers hostage

**Comment by ivalylo** [comment]
Here is an old answer from one of the Brave developers:

"The problem is that ReCaptcha relies on user tracking and fingerprinting, both things that Brave does its best to reduce or eliminate for privacy reasons.
Note that this doesn’t have anything to do with the user agent string because Brave currently uses the same user agent string as Chrome."

Seems to me, sites that use products like ReCaptcha, do not value user privacy

**Comment by snowbound** [comment]
YWhat do you expect from PayPal

**Comment by lachlansleight** [comment]
I have noticed that very recently ReCaptcha on Brave has become *extremely* frustrating. While previously one or perhaps two challenges would be presented, I'm now solving 10+ challenges with every ReCaptcha I'm presented, even when on a single site in a single session. It's funny - it'll take me 20 seconds to fill in a form, but then several minutes to complete the ReCaptcha verification at the end. Hopefully Google is getting some good machine vision training data out of me!

**Comment by fristys** [comment]
Any non Google Chrome browser gets bombarded with reCaptcha that "fails". I wish I could tell you the amount of hydrants, bikes, busses, traffic lights, and God knows what else I've had to click on, not to mention when it starts getting needlessly slow with the fade in and out. (I'm starting to question my intelligence and vision at this point)

Google folks working on this project, what's the end goal of your superiors here? To waste people's time and frustrate them into submission? Because it's not working. I'm simply going to stop using the sites that implement this. If the goal is to keep out spambots, that's not working either - it's laughably easy to get around your system for a bot.

The only thing reCaptcha keeps out is legitimate users. It's just sad.

**Comment by benjamincombes** [comment]
Same for me, I need 4 to 6 minutes to log in to EVERY SINGLE SITE with reCaptcha, worse than hell. Really, that's not possible.....!!! It asks for 4, 5...10 steps verifications on every site for a few weeks on Brave, and takes 5 seconds to load each new image on a 500Mbps connection...

**Comment by snowbound** [comment]
Apparently, the release version of Brave has a fixed rolled out to it but Brave Beta still has the issue as the fix has not hit the bea build yet.

**Comment by ukheather** [comment]
I am having this issue too. Plus they are super slow to load!
Slow loading and saying you are wrong when you aren't.

**Comment by ryanbr** [comment]
Seems fine here @ukheather   Testing via https://recaptcha-demo.appspot.com/recaptcha-v2-checkbox.php

**Comment by lachlansleight** [comment]
Yes this has been fixed for me for some time now.

**Comment by ryanbr** [comment]
Closing this, was resolved some time ago. Ensure you're using the latest ver of Brave.

**Comment by curea** [comment]
I appreciate all the "This issue was fixed a long time ago" comments on all the threads, but at least on version V1.20.108 on mac, it is not fixed and is quite annoying.

**Comment by ianks** [comment]
I cannot log in either. I'm met with a text / audio challenge that does not work. As a side note, google also made [audio is also completely incomprehensible](https://www.dropbox.com/s/7usc8jiprp4lib4/captcha.wav?dl=0)
