### ISSUE TITLE
fallback does not fire callback

### ISSUE THREAD

**Issue by defualt** [google/recaptcha#63]
The code below produces a recaptcha box with multiple images and checkboxes and "Select all images with pies." instructions and a "Verify" button.

```
    <script>
        function recaptcha_callback (){
            console.log('RECAPTCHA CALLBACK!!',arguments);
        }
    </script>
    <script src="https://www.google.com/recaptcha/api.js?fallback=true" async defer></script>
    <div class="g-recaptcha" data-sitekey="KEYKEYKEYKEY" data-callback="recaptcha_callback"></div>
```

The expected behavior is that after clicking all the checkboxes associated with images of pies, and then clicking "Verify", the console will log "'RECAPTCHA CALLBACK!!" .  This fails.  Instead, the recaptcha box refreshes with a new set of images.

If I remove the "?fallback=true" string then the script produces a more advanced recaptcha screen, and it has the expected behavior with its callback.

The reason I'm using "fallback=true" is because I'm trying to debug my Android 2.3 use case.  Android 2.3 uses the fallback by default because it doesn't meet recaptcha's minimum requirements.  My 2.3 users are unable to get past the recaptcha because of this issue.

**Comment by rowan-m** [comment]
I'll pass this on to the team, but my suspicion here is that that because the `fallback` UI is super stripped down it may not fire the callback by design. I was just testing this here and I get the same issue as you: add the `fallback`, lose the `callback`.

However, you can still use the `g-captcha-response` in the `POST` data to do the verification when the form is submitted here (i.e. the flow shown in the example). I'll ping you back @defualt when I've got some confirmation.

**Comment by defualt** [comment]
Oh! In order to succeed with the fallback, you have to complete several screens of picture grids, arrive at the copy-and-paste section, and then submit your form.  I thought that "verify" button for each picture grid really meant "verify".  To the naive user, when the proceed through the 3 required picture grid tests, they will think they are actually failing each test, when if fact they are succeeding at a step, maybe.  And I see now that the textarea you paste into after 3 picture grids is where the form derives `g-captcha-response` for the POST.  I thought the copy and paste thing was a last ditch I'm-not-a-robot test.

This is really unusable.  Especially on Android 2.3, I am unable to paste that text.  When I long press I only get a dialog for input method.  

Is there a way to force non-fallback on old Android?

Thanks for your attention @rowan-m

**Comment by rowan-m** [comment]
While the user experience is not amazing here, it is currently working as intended since the [minimum browser requirement here is Android native browser 4.0+](https://support.google.com/recaptcha#6223828).

To copy and paste the code successfully, I needed to:
1. Long press on the first text field, tap "Select all"
2. Long press on the selected text, tap "Copy".
3. Long press in second text field, tap "Paste".

**Comment by rowan-m** [comment]
Closing super old issues. Please re-raise if still relevant.
